name: Deploy example
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_f9594cf6-260c-4776-9f39-c41267550650
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
